on:
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 
        run: |
          git log 
          pwd
          ls -lrt