on:
  pull_request:
    branches: [feature1]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0



      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v13.1

      - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "$file was added"
          done


      - name: 
        run: |
          git log 
          pwd
          ls -lrt
