on:
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "$file was added"
          done


      - name: 
        run: |
          git log 
          pwd
          ls -lrt
