on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}



      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v13.1

      # - name: 

      - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was added"
          done


      - name: 
        run: |
          echo "${{ inputs }}"
          echo "${{ github }}"
          echo "${{ inputs.base_sha }}"
          echo ${{ github.event.pull_request.head.sha }}
          git log 
          pwd
          ls -lrt
