name: api call using python
on:
  push:
    branches:
      - main

# on:
#   pull_request:
#     branches: [main]
#     types: [closed]

      

jobs:
  selectivecopy:
    name: call api from python
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0


    - name: Run python script
      run: |
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "github ref: $GITHUB_REF"
        echo "github ref name: $GITHUB_REF_NAME"
        echo "github sha: $GITHUB_SHA"
        python --version
        ./api_call.sh
        

