name: main_workflow

on:

  pull_request:
    branches: [ main, test ]
    
#   workflow_dispatch

# on:
#   repository_dispatch:
#     types: [deploy-event]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
        with:
          repository: 'nikil-sigmoid/source_code_demo1'
          ref: ${{ github.ref }}
          path: 'source_code/'
          
          
      - name: List tracked files
        run: | 
          echo "branch: $GITHUB_REF"
          cd source_code
          git checkout $GITHUB_REF
          git branch
          cd my_files
          ls -al | grep '^-'
