name: Tracked Files Workflow

on:

  push:
    branches: [ main, test ]
    
#   workflow_dispatch


# on:
#   repository_dispatch:
#     types: [deploy-event]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
        with:
          repository: 'nikil-sigmoid/source_code_demo1'
          ref: ${{ github.ref }}
          path: 'source_code/'
          
          
      - name: List tracked files
        run: | 
          echo "Latest branch is: $GITHUB_REF"
          cd source_code
          echo "Checking out the lates branch"
          git checkout $GITHUB_REF
          echo "Current branch is:"
          git branch
          cd my_files
          ls -al | grep '^-'
